/*
 * Java
 *
 * Copyright 2016 IS2T. All rights reserved.
 * Use of this source code is subject to license terms.
 */
package com.microej.demo.smarthome.style;

/**
 *
 */
public interface ClassSelectors {

	String HEADER = "HEADER";
	String FOOTER = "FOOTER";
	String BODY = "BODY";
	String FOOTER_MENU_BUTTON = "FOOTER_MENU";
	String LIGHT_WIDGET = "LIGHT_WIDGET";
	String LIGHT_PROGRESS = "LIGHT_PROGRESS";
	String LIGHT_TOGGLE = "LIGHT_TOGGLE";
	String PICKER = "PICKER";
	String PICKER_TITLE_LABEL = "PICKER_TITLE_LABEL";
	String PICKER_CLOSE_BUTTON = "PICKER_CLOSE_BUTTON";
	String DOOR_WIDGET = "DOOR_WIDGET";
	String TYPE = "TYPE";
	String THERMOSTAT = "THERMOSTAT";
	String THERMOSTAT_TARGET_COLOR = "THERMOSTAT_TARGET_COLOR";
	String THERMOSTAT_VALIDATE = "THERMOSTAT_VALIDATE";
	String THERMOSTAT_TOP_LABEL = "THERMOSTAT_TOP_LABEL";
	String THERMOSTAT_BOTTOM_LABEL = "THERMOSTAT_BOTTOM_LABEL";
	String THERMOSTAT_CURRENT = "THERMOSTAT_CURRENT";
	String THERMOSTAT_DIFF_VALUE = "THERMOSTAT_DIFF_VALUE";
	String THERMOSTAT_DIFF_VALUE_DEGREE = "THERMOSTAT_DIFF_VALUE_DEGREE";
	String COLOR_CORAL = "THERMOSTAT_DESIRED_HOT";
	String THERMOSTAT_DESIRED_COLD = "THERMOSTAT_DESIRED_COLD";
	String DASHBOARD_MENU = "DASHBOARD_MENU";
	String DASHBOARD_ITEM_ICON = "DASHBOARD_ITEM_ICON";
	String DASHBOARD_ITEM_TEXT = "DASHBOARD_ITEM_TEXT";
	String DASHBOARD_HUGE_TEXT = "DASHBOARD_LIGHT_COUNT";
	String DASHBOARD_POWER_CONSUMPTION = "DASHBOARD_POWER_CONSUMPTION";
	String DASHBOARD_POWER_CONSUMPTION_BAR = "DASHBOARD_POWER_CONSUMPTION_BAR";
	String DASHBOARD_LIGHT_COUNT = "DASHBOARD_LIGHT_COUNT";
	String DASHBOARD_MENU_BUTTON = "DASHBOARD_MENU_BUTTON";
	String CHART = "CHART";
	String CHART_POINT = "CHART_POINT";
	String CHART_SCROLL = "CHART_SCROLL";
	String CHART_SCALE = "chart-scale";
	String CHART_SELECTED_INFO = "chart-selected-info";
	String CHART_SELECTED_VALUE = "chart-selected-value";

	String TEST = "TEST";

}
