/*
 * Java
 *
 * Copyright 2016 IS2T. All rights reserved.
 * Use of this source code is subject to license terms.
 */
package com.microej.demo.smarthome.style;

/**
 * The class selectors used for the style.
 */
public interface ClassSelectors {

	/**
	 * HEADER.
	 */
	String HEADER = "HEADER"; //$NON-NLS-1$

	/**
	 * FOOTER.
	 */
	String FOOTER = "FOOTER"; //$NON-NLS-1$

	/**
	 * BODY.
	 */
	String BODY = "BODY"; //$NON-NLS-1$

	/**
	 * FOOTER_MENU_BUTTON.
	 */
	String FOOTER_MENU_BUTTON = "FOOTER_MENU"; //$NON-NLS-1$

	/**
	 * LIGHT_WIDGET.
	 */
	String LIGHT_WIDGET = "LIGHT_WIDGET"; //$NON-NLS-1$

	/**
	 * LIGHT_PROGRESS.
	 */
	String LIGHT_PROGRESS = "LIGHT_PROGRESS"; //$NON-NLS-1$

	/**
	 * LIGHT_TOGGLE.
	 */
	String LIGHT_TOGGLE = "LIGHT_TOGGLE"; //$NON-NLS-1$

	/**
	 * PICKER.
	 */
	String PICKER = "PICKER"; //$NON-NLS-1$

	/**
	 * PICKER_TITLE_LABEL.
	 */
	String PICKER_TITLE_LABEL = "PICKER_TITLE_LABEL"; //$NON-NLS-1$

	/**
	 * PICKER_CLOSE_BUTTON.
	 */
	String PICKER_CLOSE_BUTTON = "PICKER_CLOSE_BUTTON"; //$NON-NLS-1$

	/**
	 * DOOR_WIDGET.
	 */
	String DOOR_WIDGET = "DOOR_WIDGET"; //$NON-NLS-1$

	/**
	 * TYPE.
	 */
	String TYPE = "TYPE"; //$NON-NLS-1$

	/**
	 * THERMOSTAT.
	 */
	String THERMOSTAT = "THERMOSTAT"; //$NON-NLS-1$

	/**
	 * THERMOSTAT_TARGET_COLOR.
	 */
	String THERMOSTAT_TARGET_COLOR = "THERMOSTAT_TARGET_COLOR"; //$NON-NLS-1$

	/**
	 * THERMOSTAT_VALIDATE.
	 */
	String THERMOSTAT_VALIDATE = "THERMOSTAT_VALIDATE"; //$NON-NLS-1$

	/**
	 * THERMOSTAT_TOP_LABEL.
	 */
	String THERMOSTAT_TOP_LABEL = "THERMOSTAT_TOP_LABEL"; //$NON-NLS-1$

	/**
	 * THERMOSTAT_BOTTOM_LABEL.
	 */
	String THERMOSTAT_BOTTOM_LABEL = "THERMOSTAT_BOTTOM_LABEL"; //$NON-NLS-1$

	/**
	 * THERMOSTAT_CURRENT.
	 */
	String THERMOSTAT_CURRENT = "THERMOSTAT_CURRENT"; //$NON-NLS-1$

	/**
	 * THERMOSTAT_DIFF_VALUE.
	 */
	String THERMOSTAT_DIFF_VALUE = "THERMOSTAT_DIFF_VALUE"; //$NON-NLS-1$

	/**
	 * THERMOSTAT_DIFF_VALUE_DEGREE.
	 */
	String THERMOSTAT_DIFF_VALUE_DEGREE = "THERMOSTAT_DIFF_VALUE_DEGREE"; //$NON-NLS-1$

	/**
	 * COLOR_CORAL.
	 */
	String COLOR_CORAL = "COLOR_CORAL"; //$NON-NLS-1$

	/**
	 * THERMOSTAT_DESIRED_COLD.
	 */
	String THERMOSTAT_DESIRED_COLD = "THERMOSTAT_DESIRED_COLD"; //$NON-NLS-1$

	/**
	 * DASHBOARD_MENU.
	 */
	String DASHBOARD_MENU = "DASHBOARD_MENU"; //$NON-NLS-1$

	/**
	 * DASHBOARD_ITEM_ICON.
	 */
	String DASHBOARD_ITEM_ICON = "DASHBOARD_ITEM_ICON"; //$NON-NLS-1$

	/**
	 * DASHBOARD_ITEM_TEXT.
	 */
	String DASHBOARD_ITEM_TEXT = "DASHBOARD_ITEM_TEXT"; //$NON-NLS-1$

	/**
	 * DASHBOARD_HUGE_TEXT.
	 */
	String DASHBOARD_HUGE_TEXT = "DASHBOARD_HUGE_TEXT"; //$NON-NLS-1$

	/**
	 * DASHBOARD_POWER_CONSUMPTION.
	 */
	String DASHBOARD_POWER_CONSUMPTION = "DASHBOARD_POWER_CONSUMPTION"; //$NON-NLS-1$

	/**
	 * DASHBOARD_POWER_CONSUMPTION_BAR.
	 */
	String DASHBOARD_POWER_CONSUMPTION_BAR = "DASHBOARD_POWER_CONSUMPTION_BAR"; //$NON-NLS-1$

	/**
	 * DASHBOARD_LIGHT_COUNT.
	 */
	String DASHBOARD_LIGHT_COUNT = "DASHBOARD_LIGHT_COUNT"; //$NON-NLS-1$

	/**
	 * DASHBOARD_MENU_BUTTON.
	 */
	String DASHBOARD_MENU_BUTTON = "DASHBOARD_MENU_BUTTON"; //$NON-NLS-1$

	/**
	 * CHART.
	 */
	String CHART = "CHART"; //$NON-NLS-1$

	/**
	 * CHART_POINT.
	 */
	String CHART_POINT = "CHART_POINT"; //$NON-NLS-1$

	/**
	 * CHART_SCROLL.
	 */
	String CHART_SCROLL = "CHART_SCROLL"; //$NON-NLS-1$

	/**
	 * CHART_SCALE.
	 */
	String CHART_SCALE = "CHART_SCALE"; //$NON-NLS-1$

	/**
	 * CHART_SELECTED_INFO.
	 */
	String CHART_SELECTED_INFO = "CHART_SELECTED_INFO"; //$NON-NLS-1$

	/**
	 * CHART_SELECTED_VALUE.
	 */
	String CHART_SELECTED_VALUE = "CHART_SELECTED_VALUE"; //$NON-NLS-1$

	/**
	 * PICKER_PLAIN_BACKGROUND.
	 */
	String PICKER_PLAIN_BACKGROUND = "PLAIN_BACKGROUND"; //$NON-NLS-1$
}
